# Практикум №5: Побудова асоцiативних правил за алгоритмами Apriori та FP-росту

0. Імпорт залежностей.

In [ ]:
import random
import numpy as np
import pandas as pd

from mlxtend.frequent_patterns import apriori, fpgrowth
from mlxtend.preprocessing import TransactionEncoder

from src.data.util.dataset import download_and_unzip
from src.definitions import EXTERNAL_DATA_FOLDER

random_seed = 42

random.seed(random_seed)
np.random.seed(random_seed)
rng = np.random.RandomState(random_seed)

1. Взяти файл з даними у вiдповiдностi з варiантом.

In [2]:
ds_path = download_and_unzip(
    "sulmansarwar", "transactions-from-a-bakery", EXTERNAL_DATA_FOLDER
)
df = pd.read_csv(ds_path / "BreadBasket_DMS.csv")

df.head()

         Date      Time  Transaction           Item
0  2016-10-30  09:58:11            1          Bread
1  2016-10-30  10:05:34            2   Scandinavian
2  2016-10-30  10:05:34            2   Scandinavian
3  2016-10-30  10:07:57            3  Hot chocolate
4  2016-10-30  10:07:57            3            Jam

In [3]:
df = df.drop(["Date", "Time"], axis=1)
df = df.dropna()

In [4]:
grouped = df.groupby("Transaction")["Item"].apply(set).apply(list).tolist()

In [5]:
te = TransactionEncoder()
te_ary = te.fit(grouped).transform(grouped)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,Adjustment,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Bacon,Baguette,Bakewell,Bare Popcorn,Basket,...,The BART,The Nomad,Tiffin,Toast,Truffles,Tshirt,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9526,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9527,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
9528,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9529,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9530,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

2. Побудувати частi набори та асоцiативнi правила (АП), використовуючи алгоритм Apriori. Дослiдити множини АП залежно вiд параметрiв побудови АП:
* мiнiмальної пiдтримки,
* мiнiмальної достовiрностi,
* максимальної потужностi частих наборiв.<br/><br/>
Пiдiбрати значення параметрiв алгоритму Apriori, якi призводять до значущих АП. АП Rk вважати значущим, якщо покращення (improvement або лiфт (lift)): Improv(Rk) > 1.

In [6]:
apriori(df, min_support=0.05)

     support  itemsets
0   0.324940      (11)
1   0.103137      (15)
2   0.475081      (23)
3   0.054034      (26)
4   0.057916      (48)
5   0.061379      (55)
6   0.079005      (62)
7   0.085510      (66)
8   0.071346      (74)
9   0.141643      (84)
10  0.089393  (11, 23)
11  0.054349  (23, 15)

3. Побудувати частi набори та множину АП, використовуючи алгоритм FP-росту. Дослiдити множини АП залежно вiд параметрiв побудови АП, якi було наведено вище для Apriori. Пiдiбрати значення параметрiв алгоритму FP-росту, якi призводять до значущих АП.

In [7]:
fpgrowth(df, min_support=0.05)

     support  itemsets
0   0.324940      (11)
1   0.057916      (48)
2   0.054034      (26)
3   0.475081      (23)
4   0.085510      (66)
5   0.061379      (55)
6   0.141643      (84)
7   0.079005      (62)
8   0.103137      (15)
9   0.071346      (74)
10  0.089393  (11, 23)
11  0.054349  (23, 15)

4. Зробити висновки щодо впливу параметрiв алгоритмiв Apriori та FP-росту на знайденi множини АП.

* Зменшення min_support збільшує кількість кандидатів

5. Знайти значення прогнозу на основi побудованої множини правил.

In [8]:
print(f"Найчастіше разом купують {df.columns[11]} та {df.columns[23]}")

Найчастіше разом купують Bread та Coffee

6. Порiвняти результати, отриманi алгоритмами Apriori та FP-росту.

* Результати однакові